apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: ${job.name}
spec:
  slotsPerWorker: ${mpi.slotsPerWorker}
  runPolicy:
    cleanPodPolicy: running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: mpi-launcher
              image: ${job.image}
              command:
                - mpirun
                - --allow-run-as-root
                - -np
                - "${mpi.orkerReplicas}"
                - -bind-to
                - none
                - -map-by
                - slot
                - "${job.executable}"
                - "${job.powMin}"
                - "${job.powMax}"
    Worker:
      replicas: ${mpi.workerReplicas}
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: mpi-worker
              image: ${job.image}