FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
    build-essential \
    openmpi-bin \
    libopenmpi-dev \
    libomp-dev \
    libomp5 \
    libgomp1 \
    make

WORKDIR /app

COPY engine/ .

RUN make

RUN chmod +x /app/build/gol-hybrid

ENTRYPOINT ["mpirun", "--allow-run-as-root", "--oversubscribe", "--mca", "plm_rsh_agent", "/bin/true", "-np", "1", "/app/build/gol-hybrid", "2", "4"]
